"""
Telegram Messaging Connector
============================
WHY: Provides the bridge between the AI agent and the Telegram chat network.
WHAT: Simple integration with the Telegram Bot API (HTTP-based).
HOW: Uses a Bot Token (from BotFather) to POST data to the Telegram servers.
"""

import requests
from core.settings import settings
import logging

class TelegramHandler:
    """
    Handles outbound responses to Telegram users.
    Unlike Twilio, Telegram uses a simple HTTP POST request to its public API URL.
    """
    def __init__(self):
        # The unique identifier for the bot in the Telegram ecosystem.
        self.bot_token = settings.TELEGRAM_BOT_TOKEN
        # Standard Telegram API endpoint for sending text messages.
        self.api_url = f"https://api.telegram.org/bot{self.bot_token}/sendMessage"

    def send_message(self, chat_id: str, text: str):
        """
        Pushes a text message back to the user's private chat.
        
        Args:
            chat_id: The unique recipient ID retrieved from the incoming webhook.
            text: The response text generated by the Gemini model.
        """
        if not self.bot_token:
            logging.error("FATAL: Telegram bot token not found in your .env configuration.")
            return False
        
        # Telegram API expects chat_id and text in the JSON body.
        data = {
            "chat_id": chat_id,
            "text": text
        }
        
        try:
            # Using the 'requests' library to execute the sync call to Telegram.
            response = requests.post(self.api_url, json=data)
            response.raise_for_status()
            return response.json()
        except Exception as e:
            logging.error(f"Telegram API Error: {e}")
            return False

# Single instance for app-wide use.
telegram_handler = TelegramHandler()
