"""
Twilio Messaging Connector
==========================
WHY: Acts as the physical gateway to the WhatsApp network.
WHAT: A wrapper around the Twilio REST API.
HOW: Uses Account SID and Auth Token to authenticate and send outbound WhatsApp messages.
"""

from twilio.rest import Client
from core.settings import settings
import logging

class TwilioHandler:
    """
    Handles all outbound communication via Twilio.
    - Lifecycle: Initialized once as a singleton.
    - fail-safe: Checks for API keys before attempting to send.
    """
    def __init__(self):
        # Client initialization using credentials from core/settings.py
        self.client = None
        if settings.TWILIO_ACCOUNT_SID and settings.TWILIO_AUTH_TOKEN:
            self.client = Client(settings.TWILIO_ACCOUNT_SID, settings.TWILIO_AUTH_TOKEN)
        # The 'From' number configured in Twilio Sandbox or Production.
        self.from_whatsapp_number = settings.TWILIO_WHATSAPP_NUMBER

    def send_whatsapp_message(self, to_number: str, message_body: str):
        """
        Sends a plain text message to a specific WhatsApp number.
        
        Args:
            to_number: The recipient's phone number (with or without 'whatsapp:' prefix).
            message_body: The text content generated by the AI.
        """
        if not self.client:
            logging.error("Twilio client not initialized. Check TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN in your .env")
            return False
        
        try:
            # Twilio's WhatsApp API requires the 'whatsapp:' prefix for both 'to' and 'from'.
            if not to_number.startswith("whatsapp:"):
                to_number = f"whatsapp:{to_number}"
            
            from_number = self.from_whatsapp_number
            if not from_number.startswith("whatsapp:"):
                from_number = f"whatsapp:{from_number}"

            # Execute the API call
            message = self.client.messages.create(
                body=message_body,
                from_=from_number,
                to=to_number
            )
            return message.sid
        except Exception as e:
            logging.error(f"FATAL: Error sending Twilio message: {e}")
            return False

    def send_whatsapp_template(self, to_number: str, content_sid: str, content_variables: str):
        """
        Sends a WhatsApp message using a predefined Content Template.
        
        Args:
            to_number: Recipient phone number (e.g., 'whatsapp:+880...')
            content_sid: The Twilio SID for the template (e.g., 'HXb5b...')
            content_variables: JSON string of variables for the template (e.g., '{"1":"12/1","2":"3pm"}')
        """
        if not self.client:
            logging.error("Twilio client not initialized. Check TWILIO_ACCOUNT_SID and TWILIO_AUTH_TOKEN in your .env")
            return False
            
        try:
            if not to_number.startswith("whatsapp:"):
                to_number = f"whatsapp:{to_number}"
                
            from_number = self.from_whatsapp_number
            if not from_number.startswith("whatsapp:"):
                from_number = f"whatsapp:{from_number}"

            message = self.client.messages.create(
                from_=from_number,
                content_sid=content_sid,
                content_variables=content_variables,
                to=to_number
            )
            return message.sid
        except Exception as e:
            logging.error(f"FATAL: Error sending Twilio template message: {e}")
            return False

# Create a single instance to be reused across the application.
twilio_handler = TwilioHandler()
